Public Class EmployeeTimeRecordResponse
    Public Property id As Integer
    Public Property employee As EmployeeResponse
    Public Property payroll_period As PayrollPeriodResponse
    Public Property computed_salary As EmployeeComputedSalaryResponse
    Public Property total_working_minutes As Decimal
    Public Property total_working_minutes_with_leave As Decimal
    Public Property total_working_hours As Decimal
    Public Property total_working_hours_with_leave As Decimal
    Public Property total_overtime_minutes As Decimal
    Public Property total_undertime_minutes As Decimal
    Public Property total_official_business_minutes As Decimal
    Public Property total_official_time_minutes As Decimal
    Public Property total_leave_minutes As Decimal
    Public Property total_night_duty_hours As Decimal
    Public Property no_of_present_days As Decimal
    Public Property no_of_present_days_with_leave As Decimal
    Public Property no_of_leave_wo_pay As Decimal
    Public Property no_of_leave_w_pay As Decimal
    Public Property no_of_absences As Decimal
    Public Property no_of_invalid_entry As Decimal
    Public Property no_of_day_off As String
    Public Property no_of_schedule As String
    Public Property night_duties As String
    Public Property absent_dates As String
    Public Property month As String
    Public Property year As String
    Public Property date_from As String
    Public Property date_to As String
    Public Property status As String
    Public Property is_active As Integer
    Public Property locked_at As String
    Public Property created_at As String
    Public Property updated_at As String
    Public Property deleted_at As String
End Class
